spring.application.name=hospitalz
spring.datasource.url=jdbc:mysql://localhost:3306/hospital_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Illuminati12354!

# MySQL driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server port (optional, but good if you want it running on 8080)
server.port=8080